sudo: required
services: 
  - docker

before_install:
  - docker build -t lca/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lca/docker-react npm run test

language: generic